export enum LobbyType {
  Casual = 0,
  Practice = 1,
  Tournament = 2,
  Tutorial = 3,
  Bots = 4,
  TeamMatch = 5,
  SoloQueue = 6,
  Ranked = 7,
  SoloMid = 9,
}

export enum GameMode {
  Unknown = 0,
  AllPick = 1,
  CaptainsMode = 2,
  RandomDraft = 3,
  SingleDraft = 4,
  TeamAllRandom = 5,
  Intro = 6,
  Diretide = 7,
  ReverseCaptainMode = 8,
  Greeviling = 9,
  Tutorial = 10,
  MidOnly = 11,
  LeastPlayed = 12,
  LimitedHeroes = 13,
  Compendium = 14,
  Custom = 15,
  CaptainsDraft = 16,
  BalancedDraft = 17,
  AbilityDraft = 18,
  Event = 19,
  RdDeathMatch = 20,
  OneVsOneMid = 21,
  AllDraft = 22,
  Turbo = 23,
  Mutation = 24,
  CoachChallenge = 25,
}
